mkdir: cannot create directory ‚Äò/scr/drew/‚Äô: File exists
rsync: link_stat "/net/mahler/home/mscbio/anm329/deltadeltaG/DDG_model.py" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1196) [sender=3.1.2]
Running on n078.dcb.private.net
PATH=/net/pulsar/home/koes/dkoes/local/bin:/net/mahler/home/mscbio/anm329/bin:/opt/slurm/slurm-19.05.1-2/bin:/opt/slurm/slurm-19.05.1-2/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/:/net/pulsar/home/koes/dkoes/local/cuda-10.1/lib64:/net/pulsar/home/koes/dkoes/local/lib:/net/antonin/usr/local/cuda-10.0/lib64:/usr/lib64:/usr/lib/x86_64-linux-gnu:/usr/local/cuda-10.0/lib64:/lib:
PYTHONPATH=/net/pulsar/home/koes/dkoes/local/lib/python3.6/site-packages/:
SCRDIR=/scr/drew



wandb: Tracking run with wandb version 0.8.13
wandb: Wandb version 0.8.21 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Run data is saved locally in wandb/run-20200121_221933-gqoc5mby
wandb: Syncing run electric-snowflake-81
wandb: ‚≠êÔ∏è View project at https://app.wandb.ai/andmcnutt/DDG_model
wandb: üöÄ View run at https://app.wandb.ai/andmcnutt/DDG_model/runs/gqoc5mby
wandb: Run `wandb off` to turn off syncing.

DDG_reg.py:61: UserWarning: Using a target size (torch.Size([42])) that is different to the input size (torch.Size([1, 42, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  loss = F.mse_loss(output,labels)
DDG_reg.py:82: UserWarning: Using a target size (torch.Size([42])) that is different to the input size (torch.Size([1, 42, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  loss = F.mse_loss(output,labels)
Traceback (most recent call last):
  File "DDG_reg.py", line 137, in <module>
    "Test R^2": tt_r2})
  File "/net/mahler/home/mscbio/anm329/.local/lib/python3.6/site-packages/wandb/__init__.py", line 667, in log
    run.history.add(row, *args, step=step, **kwargs)
  File "/net/mahler/home/mscbio/anm329/.local/lib/python3.6/site-packages/wandb/history.py", line 126, in add
    self._write()
  File "/net/mahler/home/mscbio/anm329/.local/lib/python3.6/site-packages/wandb/history.py", line 225, in _write
    self._file.write(util.json_dumps_safer_history(self.row))
  File "/net/mahler/home/mscbio/anm329/.local/lib/python3.6/site-packages/wandb/util.py", line 449, in json_dumps_safer_history
    return json.dumps(obj, cls=WandBHistoryJSONEncoder, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in ite
rencode
    return _iterencode(o, 0)
  File "/net/mahler/home/mscbio/anm329/.local/lib/python3.6/site-packages/wandb/util.py", line 435, in default
    obj, converted = json_friendly(obj)
  File "/net/mahler/home/mscbio/anm329/.local/lib/python3.6/site-packages/wandb/util.py", line 295, in json_friendly
    obj = obj.numpy()
TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/net/mahler/home/mscbio/anm329/.local/lib/python3.6/site-packages/wandb/history.py", line 225, in _write
    self._file.write(util.json_dumps_safer_history(self.row))
  File "/net/mahler/home/mscbio/anm329/.local/lib/python3.6/site-packages/wandb/util.py", line 449, in json_dumps_safer_history
    return json.dumps(obj, cls=WandBHistoryJSONEncoder, **kwargs)
  File "/usr/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    wandb: Waiting for W&B process to finish, PID 4307
chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/net/mahler/home/mscbio/anm329/.local/lib/python3.6/site-packages/wandb/util.py", line 435, in default
    obj, converted = json_friendly(obj)
  File "/net/mahler/home/mscbio/anm329/.local/lib/python3.6/site-packages/wandb/util.py", line 295, in json_friendly
    obj = obj.numpy()
TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
wandb: Program failed with code 1. Press ctrl-c to abort syncing.
wandb: Run summary:
wandb: Syncing 7 W&B file(s) and 0 media file(s)
wandb: - 0.00MB of 0.00MB uploadedwandb: \ 0.00MB of 0.00MB uploadedwandb: | 0.00MB of 0.00MB uploadedwandb: / 0.00MB of 0.00MB uploadedwandb: - 0.00MB of 0.00MB uploadedwandb: \ 0.00MB of 0.00MB uploadedwandb:                                                                                
wandb: Synced electric-snowflake-81: https://app.wandb.ai/andmcnutt/DDG_model/runs/gqoc5mby
/var/lib/slurm-llnl/slurmd/job72891/slurm_script: line 32: cmd: command not found
